# Configuration for misinformation detection model
batch_size: 128
learning_rate: 0.001
hidden_dim: 64
tfidf_max_features: 5000

# Model parameters
model:
  tgn:
    memory_dim: 100
    time_dim: 100
    message_dim: 100
    embedding_dim: 100
    n_heads: 2
    dropout: 0.1
    use_memory: true
  
  gcn:
    hidden_channels: 100
    num_layers: 2
    dropout: 0.1

# Training settings
training:
  epochs: 100
  patience: 10
  val_ratio: 0.15
  test_ratio: 0.15
  eval_frequency: 1
  
# Paths
paths:
  coaid:
    raw: data/raw/coaid
    processed: data/processed/coaid_processed.pkl
  fakenewsnet:
    raw: data/raw/fakenewsnet
    processed: data/processed/fakenewsnet_processed.pkl
  results: results/
